### ISSUE TITLE
Unsure RelayX Browser Extension works in Brave

### ISSUE THREAD

**Issue by derrickhorton** [pow-co/relayx-browser-extension#13]
I am having a weird issue when trying to boost on Pow.co using the RelayX Browser Extension. 

I am signed into the Relay Browser Extension. 

So theoretically, I wanted to test "Shields Up" on Brave to make sure that it is using the Extension and not the regular page login.

But it keeps asking me to log in over and over again when I boost, and it won't do the boost.

Then when I put "Shields Down" (the old way), and log in, it boosts fine.

So I am not able to use the Browser Extension as intended. 

Video:

https://user-images.githubusercontent.com/4019818/219051196-54a3ff54-015f-4026-af7d-6e33fd595a24.mp4

**Comment by relayking** [comment]
Just tested and it works. You should see connected to extension toaster on relayx.com when everything is setup correctly.
